### ISSUE TITLE
shinymixR

### ISSUE THREAD

**Issue by harishkaushikbugworks** [nlmixrdevelopment/nlmixr#256]
Hello,
Iam trying to install shinymixR by typing the following code

> devtools::install_github("richardhooijmaijers/shinyMixR")

but i got the following message in R studio
Skipping install of 'shinyMixR' from a github remote, the SHA1 (84b8ba46) has not changed since last install.
  Use `force = TRUE` to force installation

Can you help me with this

my nlmixR is working properly, only shinymixR is not working

Thanks
Harish

**Comment by mattfidler** [comment]
Hi Harish,

If you are using windows the easiest solution is to use the installer.  

https://github.com/nlmixrdevelopment/nlmixr/releases

In theory it should work.  The error you are getting means you already have the latest shinyMixR.

Perhaps @RichardHooijmaijers can help here.  

The ShinyMixR repository is here, you could file a bug report:

www.github.com/richardhooijmaijers/shinyMixR

**Comment by RichardHooijmaijers** [comment]
I agree with @mattfidler that it would be better to file a bug report on the shinyMixR repo. I looked into the issue and found out that it has to do with incompatibility between the latest shiny version and the shinyBS package [see link](https://github.com/ebailey78/shinyBS/issues/112). This has great consequences for the shinyMixR package, because the combination of these packages is widely used by shinyMixR. I will start updating the package and hope to come with a solution asap but might take some time

**Comment by harishkaushikbugworks** [comment]
Thanks Richard

**Comment by nsk64** [comment]
Hello,
I have installed shinymixR and the run_shinymixr(wd=mypathloc, launch.brower = TRUE) command launch the shiny interface.
However nothing appeared in the "overview" and the "Project selection" button leads to empty fields. Also, I cannot select any folder.
Could you give any advice?
Best regards
Nicolas

**Comment by mattfidler** [comment]
It seems this is a problem with shinyBS. @RichardHooijmaijers  is working hard on a fix for this.  Once it is done, updating `shinyMixR` should do the trick.

**Comment by RichardHooijmaijers** [comment]
I just updated the `shinyMixR` package. This is a major update and it should solve the issues. Could you please run:
`devtools::install_github("richardhooijmaijers/shinyMixR")`
and see if this solves the problems you are having?

**Comment by nsk64** [comment]
Hi

after re-installing digest by my own I have an empty page with:

ERROR: Error sourcing C:\Users\nicol\AppData\Local\Temp\RtmpYhgN6M\file424738571ba

The R code:


> run_shinymixr(wd=path_loc,launch.browser = TRUE)


Listening on http://127.0.0.1:3422
Error : '\U' used without hex digits in character string starting "'C:\U"
Warning: Error in sourceUTF8: Error sourcing C:\Users\nicol\AppData\Local\Temp\RtmpYhgN6M\file4242a716719
  [No stack trace available]


Best regards

Nicolas


________________________________
De : RichardHooijmaijers <notifications@github.com>
Envoyé : vendredi 13 décembre 2019 16:48
À : nlmixrdevelopment/nlmixr
Cc : SIMON Nicolas; Comment
Objet : Re: [nlmixrdevelopment/nlmixr] shinymixR (#256)


I just updated the shinyMixR package. This is a major update and it should solve the issues. Could you please run:
devtools::install_github("richardhooijmaijers/shinyMixR")
and see if this solves the problems you are having?

-

**Comment by mattfidler** [comment]
You need to restart R then:

```r
install.packages("digest")
devtools::install_github("richardhooijmaijers/shinyMixR")
```

**Comment by nsk64** [comment]
I still have the same result:


> run_shinymixr(wd=path_loc,launch.browser = TRUE)

Listening on http://127.0.0.1:7319
Error : '\U' used without hex digits in character string starting "'C:\U"
Warning: Error in sourceUTF8: Error sourcing C:\Users\nicol\AppData\Local\Temp\RtmpC2azrk\file578bc51e03
  [No stack trace available]
Error : '\U' used without hex digits in character string starting "'C:\U"
Warning: Error in sourceUTF8: Error sourcing C:\Users\nicol\AppData\Local\Temp\RtmpC2azrk\file5785d6f2e4f
  [No stack trace available]



________________________________
De : Matthew Fidler <notifications@github.com>
Envoyé : vendredi 13 décembre 2019 19:36
À : nlmixrdevelopment/nlmixr
Cc : SIMON Nicolas; Comment
Objet : Re: [nlmixrdevelopment/nlmixr] shinymixR (#256)


You need to restart R then:

install.packages("digest")
devtools::install_github("richardhooijmaijers/shinyMixR")

-

**Comment by mattfidler** [comment]
Hi @RichardHooijmaijers 

This is the backtrace for me on Windows:

<details>

```r

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> options(keep.source=TRUE);library(shinyMixR);nlmixr:::.setRoot();run_shinymixr(launch.browser=TRUE)
Loading required package: shiny
Loading required package: nlmixr
Loading required package: ggplot2

Listening on http://127.0.0.1:5267
Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) :
  C:\Users\fidlema3\AppData\Local\Temp\1\RtmpINoVip/ui.R:15:27: unexpected symbol
14:   shinydashboard::dashboardHeader(
15:     title = tags$img(src='logoshinyMixR.png
                              ^
Possible missing comma at:
15:    title = tags$img(src='logoshinyMixR.png',height=45),
                             ^
Possible missing comma at:
15:    title = tags$img(src='logoshinyMixR.png',height=45),
                                              ^
Possible missing comma at:
16:    tags$li(img(src = 'logonlmixr.png',height=42),class = "dropdown")
                          ^
Possible missing comma at:
16:    tags$li(img(src = 'logonlmixr.png',height=42),class = "dropdown")
                                        ^
Possible missing comma at:
23:      shinydashboard::menuItem('Model overview', tabName='overview', icon=icon('folder')),
                                   ^
Possible missing comma at:
23:      shinydashboard::menuItem('Model overview', tabName='overview', icon=icon('folder')),
                                         ^
Possible missing comma at:
23:      shinydashboard::menuItem('Model overview', tabName='overview', icon=icon('folder')),
                                                 ^
Possible missing comma at:
23:      shinydashboard::menuItem('Model overview', tabName='overview', icon=icon('folder')),
                                                             ^
Possible missing comma at:
23:      shinydashboard::menuItem('Model overview', tabName='overview', icon=icon('folder')),
                                                                     ^
Possible missing comma at:
23:      shinydashboard::menuItem('Model overview', tabName='overview', icon=icon('folder')),
                                                                                   ^
Possible missing comma at:
23:      shinydashboard::menuItem('Model overview', tabName='overview', icon=icon('folder')),
                                                                                         ^
Possible missing comma at:
24:      shinydashboard::menuItem('Edit model(s)', tabName='editor', icon=icon('edit')),
                                   ^
Possible missing comma at:
24:      shinydashboard::menuItem('Edit model(s)', tabName='editor', icon=icon('edit')),
                                        ^
Possible missing comma at:
24:      shinydashboard::menuItem('Edit model(s)', tabName='editor', icon=icon('edit')),
                                                ^
Possible missing comma at:
24:      shinydashboard::menuItem('Edit model(s)', tabName='editor', icon=icon('edit')),
                                                            ^
Possible missing comma at:
24:      shinydashboard::menuItem('Edit model(s)', tabName='editor', icon=icon('edit')),
                                                                  ^
Possible missing comma at:
24:      shinydashboard::menuItem('Edit model(s)', tabName='editor', icon=icon('edit')),
                                                                                ^
Possible missing comma at:
24:      shinydashboard::menuItem('Edit model(s)', tabName='editor', icon=icon('edit')),
                                                                                    ^
Possible missing comma at:
25:      shinydashboard::menuItem('Run model(s)', tabName='run', icon=icon('forward')),
                                   ^
Possible missing comma at:
25:      shinydashboard::menuItem('Run model(s)', tabName='run', icon=icon('forward')),
                                       ^
Possible missing comma at:
25:      shinydashboard::menuItem('Run model(s)', tabName='run', icon=icon('forward')),
                                               ^
Possible missing comma at:
25:      shinydashboard::menuItem('Run model(s)', tabName='run', icon=icon('forward')),
                                                           ^
Possible missing comma at:
25:      shinydashboard::menuItem('Run model(s)', tabName='run', icon=icon('forward')),
                                                              ^
Possible missing comma at:
25:      shinydashboard::menuItem('Run model(s)', tabName='run', icon=icon('forward')),
                                                                            ^
Possible missing comma at:
25:      shinydashboard::menuItem('Run model(s)', tabName='run', icon=icon('forward')),
                                                                                   ^
Possible missing comma at:
26:      shinydashboard::menuItem('Parameter estimates', tabName='par', icon=icon('table')),
                                   ^
Possible missing comma at:
26:      shinydashboard::menuItem('Parameter estimates', tabName='par', icon=icon('table')),
                                             ^
Possible missing comma at:
26:      shinydashboard::menuItem('Parameter estimates', tabName='par', icon=icon('table')),
                                                      ^
Possible missing comma at:
26:      shinydashboard::menuItem('Parameter estimates', tabName='par', icon=icon('table')),
                                                                  ^
Possible missing comma at:
26:      shinydashboard::menuItem('Parameter estimates', tabName='par', icon=icon('table')),
                                                                     ^
Possible missing comma at:
26:      shinydashboard::menuItem('Parameter estimates', tabName='par', icon=icon('table')),
                                                                                   ^
Possible missing comma at:
26:      shinydashboard::menuItem('Parameter estimates', tabName='par', icon=icon('table')),
                                                                                        ^
Possible missing comma at:
27:      shinydashboard::menuItem('Goodness of fit', tabName='gof', icon=icon('chart-line')),
                                   ^
Possible missing comma at:
27:      shinydashboard::menuItem('Goodness of fit', tabName='gof', icon=icon('chart-line')),
                                            ^
Possible missing comma at:
27:      shinydashboard::menuItem('Goodness of fit', tabName='gof', icon=icon('chart-line')),
                                               ^
Possible missing comma at:
27:      shinydashboard::menuItem('Goodness of fit', tabName='gof', icon=icon('chart-line')),
                                                  ^
Possible missing comma at:
27:      shinydashboard::menuItem('Goodness of fit', tabName='gof', icon=icon('chart-line')),
                                                              ^
Possible missing comma at:
27:      shinydashboard::menuItem('Goodness of fit', tabName='gof', icon=icon('chart-line')),
                                                                 ^
Possible missing comma at:
27:      shinydashboard::menuItem('Goodness of fit', tabName='gof', icon=icon('chart-line')),
                                                                               ^
Possible missing comma at:
27:      shinydashboard::menuItem('Goodness of fit', tabName='gof', icon=icon('chart-line')),
                                                                                         ^
Possible missing comma at:
28:      shinydashboard::menuItem('Fit plots', tabName='fit', icon=icon('chart-line')),
                                   ^
Possible missing comma at:
28:      shinydashboard::menuItem('Fit plots', tabName='fit', icon=icon('chart-line')),
                                       ^
Possible missing comma at:
28:      shinydashboard::menuItem('Fit plots', tabName='fit', icon=icon('chart-line')),
                                            ^
Possible missing comma at:
28:      shinydashboard::menuItem('Fit plots', tabName='fit', icon=icon('chart-line')),
                                                        ^
Possible missing comma at:
28:      shinydashboard::menuItem('Fit plots', tabName='fit', icon=icon('chart-line')),
                                                           ^
Possible missing comma at:
28:      shinydashboard::menuItem('Fit plots', tabName='fit', icon=icon('chart-line')),
                                                                         ^
Possible missing comma at:
28:      shinydashboard::menuItem('Fit plots', tabName='fit', icon=icon('chart-line')),
                                                                                   ^
Possible missing comma at:
29:      shinydashboard::menuItem('Scripts', tabName='script', icon=icon('terminal')),
                                   ^
Possible missing comma at:
29:      shinydashboard::menuItem('Scripts', tabName='script', icon=icon('terminal')),
                                          ^
Possible missing comma at:
29:      shinydashboard::menuItem('Scripts', tabName='script', icon=icon('terminal')),
                                                      ^
Possible missing comma at:
29:      shinydashboard::menuItem('Scripts', tabName='script', icon=icon('terminal')),
                                                            ^
Possible missing comma at:
29:      shinydashboard::menuItem('Scripts', tabName='script', icon=icon('terminal')),
                                                                          ^
Possible missing comma at:
29:      shinydashboard::menuItem('Scripts', tabName='script', icon=icon('terminal')),
                                                                                  ^
Possible missing comma at:
30:      shinydashboard::menuItem('Analysis results', tabName='results', icon=icon('book')),
                                   ^
Possible missing comma at:
30:      shinydashboard::menuItem('Analysis results', tabName='results', icon=icon('book')),
                                            ^
Possible missing comma at:
30:      shinydashboard::menuItem('Analysis results', tabName='results', icon=icon('book')),
                                                   ^
Possible missing comma at:
30:      shinydashboard::menuItem('Analysis results', tabName='results', icon=icon('book')),
                                                               ^
Possible missing comma at:
30:      shinydashboard::menuItem('Analysis results', tabName='results', icon=icon('book')),
                                                                      ^
Possible missing comma at:
30:      shinydashboard::menuItem('Analysis results', tabName='results', icon=icon('book')),
                                                                                    ^
Possible missing comma at:
30:      shinydashboard::menuItem('Analysis results', tabName='results', icon=icon('book')),
                                                                                        ^
Possible missing comma at:
31:      shinydashboard::menuItem('Settings', tabName='settings', icon=icon('cog'))
                                   ^
Possible missing comma at:
31:      shinydashboard::menuItem('Settings', tabName='settings', icon=icon('cog'))
                                           ^
Possible missing comma at:
31:      shinydashboard::menuItem('Settings', tabName='settings', icon=icon('cog'))
                                                       ^
Possible missing comma at:
31:      shinydashboard::menuItem('Settings', tabName='settings', icon=icon('cog'))
                                                               ^
Possible missing comma at:
31:      shinydashboard::menuItem('Settings', tabName='settings', icon=icon('cog'))
                                                                             ^
Possible missing comma at:
31:      shinydashboard::menuItem('Settings', tabName='settings', icon=icon('cog'))
                                                                                ^
Possible missing comma at:
37:    tags$head(tags$style(HTML('.sidebar-menu > li > a{padding: 5px 5px 5px 15px;}'))),
                                  ^
Possible missing comma at:
39:      shinydashboard::tabItem(tabName='overview',overviewfuncUI()),
                                          ^
Possible missing comma at:
39:      shinydashboard::tabItem(tabName='overview',overviewfuncUI()),
                                                  ^
Possible missing comma at:
40:      shinydashboard::tabItem(tabName='editor',editorfuncUI()),
                                          ^
Possible missing comma at:
40:      shinydashboard::tabItem(tabName='editor',editorfuncUI()),
                                                ^
Possible missing comma at:
41:      shinydashboard::tabItem(tabName='run',runfuncUI()),
                                          ^
Possible missing comma at:
41:      shinydashboard::tabItem(tabName='run',runfuncUI()),
                                             ^
Possible missing comma at:
42:      shinydashboard::tabItem(tabName='par',parfuncUI()),
                                          ^
Possible missing comma at:
42:      shinydashboard::tabItem(tabName='par',parfuncUI()),
                                             ^
Possible missing comma at:
43:      shinydashboard::tabItem(tabName='gof',goffuncUI()),
                                          ^
Possible missing comma at:
43:      shinydashboard::tabItem(tabName='gof',goffuncUI()),
                                             ^
Possible missing comma at:
44:      shinydashboard::tabItem(tabName='fit',fitfuncUI()),
                                          ^
Possible missing comma at:
44:      shinydashboard::tabItem(tabName='fit',fitfuncUI()),
                                             ^
Possible missing comma at:
45:      shinydashboard::tabItem(tabName='script',scriptfuncUI()),
                                          ^
Possible missing comma at:
45:      shinydashboard::tabItem(tabName='script',scriptfuncUI()),
                                                ^
Possible missing comma at:
46:      shinydashboard::tabItem(tabName='results',resultsfuncUI()),
                                          ^
Possible missing comma at:
46:      shinydashboard::tabItem(tabName='results',resultsfuncUI()),
                                                 ^
Possible missing comma at:
47:      shinydashboard::tabItem(tabName='settings',settingsfuncUI())
                                          ^
Warning: Error in sourceUTF8: Error sourcing C:\Users\fidlema3\AppData\Local\Temp\1\RtmpINoVip\file3a3430b657a0
  [No stack trace available]
```

</details>

**Comment by RichardHooijmaijers** [comment]
I am sorry but I did not do proper testing in windows. I just changed an important part of the code and tested it in a windows environment. Everything work out for me now, could you please reinstall using `devtools::install_github("richardhooijmaijers/shinyMixR")` and let me know if it works?

**Comment by nsk64** [comment]
The installation seems to be successful.

However when I tried to run the run1 on theo_sd, it crashed without any warning.


________________________________
De : RichardHooijmaijers <notifications@github.com>
Envoyé : samedi 14 décembre 2019 15:50
À : nlmixrdevelopment/nlmixr
Cc : SIMON Nicolas; Comment
Objet : Re: [nlmixrdevelopment/nlmixr] shinymixR (#256)


I am sorry but I did not do proper testing in windows. I just changed an important part of the code and tested it in a windows environment. Everything work out for me now, could you please reinstall using devtools::install_github("richardhooijmaijers/shinyMixR") and let me know if it works?

-

**Comment by nsk64** [comment]
I re-tried the following:

> path <- getwd()
> path
[1] "C:/Users/nicol/Dropbox/nm730/run/_rnsk/nlmixR"
> path_loc <- paste(path,"/theo",sep="")

> #run_shinymixr()
> run_shinymixr(wd=path_loc,launch.browser = TRUE)

Listening on http://127.0.0.1:5409
Warning in dir.create("shinyMixR/temp", recursive = TRUE) :
  'shinyMixR\temp' already exists
Warning: Error in : $ operator is invalid for atomic vectors
  55: ifelse
  54: FUN
  53: lapply
  52: overview
  51: overviewfuncSRV [srv_functions.r#5]
  50: server [C:\Users\nicol\AppData\Local\Temp\RtmpymOAPY/server.R#14]
Error : $ operator is invalid for atomic vectors


________________________________
De : RichardHooijmaijers <notifications@github.com>
Envoyé : samedi 14 décembre 2019 15:50
À : nlmixrdevelopment/nlmixr
Cc : SIMON Nicolas; Comment
Objet : Re: [nlmixrdevelopment/nlmixr] shinymixR (#256)


I am sorry but I did not do proper testing in windows. I just changed an important part of the code and tested it in a windows environment. Everything work out for me now, could you please reinstall using devtools::install_github("richardhooijmaijers/shinyMixR") and let me know if it works?

-

**Comment by RichardHooijmaijers** [comment]
Based on the error it is a bit difficult find the problem. Would it be possible to run the following lines of code in a new/clean directory, and let me know if you experience any issues here?

```
# setwd to empty directory
library(shinyMixR)
create_proj()
pr <- get_proj()
run_nmx("run1",poj=pr,ext=FALSE)
run_nmx("run1",poj=pr,ext=TRUE)
```

This would help me a lot in finding out what goes wrong.

Thanks and sorry for the inconvenience

**Comment by nsk64** [comment]
In a new project/folder, I have the following:


> pr <- get_proj()
> run_nmx("run1",poj=pr,ext = FALSE)
Error in run_nmx("run1", poj = pr, ext = FALSE) :
  unused argument (poj = pr)

> run_nmx("run1",poj=pr,ext = TRUE)
Error in run_nmx("run1", poj = pr, ext = TRUE) :
  unused argument (poj = pr)


________________________________
De : RichardHooijmaijers <notifications@github.com>
Envoyé : lundi 16 décembre 2019 11:19
À : nlmixrdevelopment/nlmixr
Cc : SIMON Nicolas; Comment
Objet : Re: [nlmixrdevelopment/nlmixr] shinymixR (#256)


Based on the error it is a bit difficult find the problem. Would it be possible to run the following lines of code in a new/clean directory, and let me know if you experience any issues here?

# setwd to empty directory
library(shinyMixR)
create_proj()
pr <- get_proj()
run_nmx("run1",poj=pr,ext=FALSE)
run_nmx("run1",poj=pr,ext=TRUE)


This would help me a lot in finding out what goes wrong.

Thanks and sorry for the inconvenience

-

**Comment by RichardHooijmaijers** [comment]
I see a made a typo (should be proj instead of poj!):

```
# setwd to empty directory
library(shinyMixR)
create_proj()
pr <- get_proj()
run_nmx("run1",proj=pr,ext=FALSE)
run_nmx("run1",proj=pr,ext=TRUE)
```

sorry for this

**Comment by nsk64** [comment]
run_nmx("run1",proj=pr,ext=FALSE)
runs within RStudio and gives an estimation.
.../...

-- Fit Data (object is a modified tibble): -------------------------------------
# A tibble: 132 x 25
  ID     TIME    DV  EVID  PRED     RES    WRES IPRED  IRES IWRES CPRED    CRES    CWRES eta.ka eta.cl
  <fct> <dbl> <dbl> <int> <dbl>   <dbl>   <dbl> <dbl> <dbl> <dbl> <dbl>   <dbl>    <dbl>  <dbl>  <dbl>
1 1     0      0.74     0  0     0.74    0.451   0     0.74  1.06  0     0.74    1.06     0.387 -0.472
2 1     0.25   2.84     0  3.50 -0.660  -0.402   4.30 -1.46 -2.10  3.52 -0.679  -0.113    0.387 -0.472
3 1     0.570  6.57     0  6.55  0.0229  0.0140  8.70 -2.13 -3.07  6.67 -0.0979 -0.00870  0.387 -0.472


while
run_nmx("run1",proj=pr,ext=TRUE)
does not




________________________________
De : RichardHooijmaijers <notifications@github.com>
Envoyé : lundi 16 décembre 2019 12:57
À : nlmixrdevelopment/nlmixr
Cc : SIMON Nicolas; Comment
Objet : Re: [nlmixrdevelopment/nlmixr] shinymixR (#256)


I see a made a typo (should be proj instead of poj!):

# setwd to empty directory
library(shinyMixR)
create_proj()
pr <- get_proj()
run_nmx("run1",proj=pr,ext=FALSE)
run_nmx("run1",proj=pr,ext=TRUE)


sorry for this

-

**Comment by RichardHooijmaijers** [comment]
Thanks, this already helps. It is expected that ypu do not see nay results in the last call because it is submitted in an external R session. You should be able to read in the iteration results using:

`readLines("shinyMixR/temp/run1.prog.txt")`

I will do some more testing if I can see what the exact problem is.

**Comment by nsk64** [comment]
It gave
character(0)


De : RichardHooijmaijers [mailto:notifications@github.com]
Envoyé : lundi 16 décembre 2019 14:44
À : nlmixrdevelopment/nlmixr <nlmixr@noreply.github.com>
Cc : SIMON Nicolas <Nicolas.SIMON@ap-hm.fr>; Comment <comment@noreply.github.com>
Objet : Re: [nlmixrdevelopment/nlmixr] shinymixR (#256)


Thanks, this already helps. It is expected that ypu do not see nay results in the last call because it is submitted in an external R session. You should be able to read in the iteration results using:

readLines("shinyMixR/temp/run1.prog.txt")

I will do some more testing if I can see what the exact problem is.

**Comment by nsk64** [comment]
run_nmx(« run1 »,proj=pr, ext=TRUE)
does not seem to run
character(0)

however I have a folder following ext=FALSE
with a file run1.progr.txt

I can try to delete it and restart ext=TRUE


De : RichardHooijmaijers [mailto:notifications@github.com]
Envoyé : lundi 16 décembre 2019 14:44
À : nlmixrdevelopment/nlmixr <nlmixr@noreply.github.com>
Cc : SIMON Nicolas <Nicolas.SIMON@ap-hm.fr>; Comment <comment@noreply.github.com>
Objet : Re: [nlmixrdevelopment/nlmixr] shinymixR (#256)


Thanks, this already helps. It is expected that ypu do not see nay results in the last call because it is submitted in an external R session. You should be able to read in the iteration results using:

readLines("shinyMixR/temp/run1.prog.txt")

I will do some more testing if I can see what the exact problem is.

**Comment by RichardHooijmaijers** [comment]
When you run the function with ext=FALSE, the results will be directly available within R and normally you would not have the run1.prog.txt in the shinyMixR/temp folder. This file is only created with ext set to TRUE. If you have it available and it has the iteration history it would mean that the ext=TRUE run was successful. If this is not the case, it is possible that the environmental variable is not correctly set for the R version that has nlmixr installed. If you run `shell("Rscript --version")` does it state the R version that has nlmixr installed?

**Comment by nsk64** [comment]
In the temp folder I do have the run1.prog.txt

It seems so fast compared to ext=FALSE!!!

version3.6.1  (2019-07-05)



De : RichardHooijmaijers [mailto:notifications@github.com]
Envoyé : lundi 16 décembre 2019 16:07
À : nlmixrdevelopment/nlmixr <nlmixr@noreply.github.com>
Cc : SIMON Nicolas <Nicolas.SIMON@ap-hm.fr>; Comment <comment@noreply.github.com>
Objet : Re: [nlmixrdevelopment/nlmixr] shinymixR (#256)


When you run the function with ext=FALSE, the results will be directly available within R and normally you would not have the run1.prog.txt in the shinyMixR/temp folder. This file is only created with ext set to TRUE. If you have it available and it has the iteration history it would mean that the ext=TRUE run was successful. If this is not the case, it is possible that the environmental variable is not correctly set for the R version that has nlmixr installed. If you run shell("Rscript --version") does it state the R version that has nlmixr installed?

**Comment by RichardHooijmaijers** [comment]
If you have the run1.prog.txt in the temp folder (and it has the iteration history), then external running shouldn't be the issue. If this file contains a lot of errors or is empty then there are issues with external running. 
The increase in speed is just apparent unfortunately. The process is submitted in a separate session. This means that you will almost immediately return to the console but the calculations are still being performed on the background. This was done so that the app is not frozen when running a model.
I will do some additional testing, later this week and let you know my findings.

**Comment by nsk64** [comment]
In run1.prog.txt file I have no error message and it ended with
Calculating residuals/tables done.
Compiling NPDE model…done


De : RichardHooijmaijers [mailto:notifications@github.com]
Envoyé : lundi 16 décembre 2019 16:21
À : nlmixrdevelopment/nlmixr <nlmixr@noreply.github.com>
Cc : SIMON Nicolas <Nicolas.SIMON@ap-hm.fr>; Comment <comment@noreply.github.com>
Objet : Re: [nlmixrdevelopment/nlmixr] shinymixR (#256)


If you have the run1.prog.txt in the temp folder (and it has the iteration history), then external running shouldn't be the issue. If this file contains a lot of errors or is empty then there are issues with external running.
The increase in speed is just apparent unfortunately. The process is submitted in a separate session. This means that you will almost immediately return to the console but the calculations are still being performed on the background. This was done so that the app is not frozen when running a model.
I will do some additional testing, later this week and let you know my findings.

**Comment by RichardHooijmaijers** [comment]
I did additional testing on a windows platform and things seems to run without a problem for me. It could be that you are missing a vital package for the app, could you try and install shinywidgets and try again?:
`install.packages("shinyWidgets")`

**Comment by nsk64** [comment]
YES
it runs.

I have 2 additional questions:
- I save "run1" as "run2" and change saem to focei but I wasn't able to run it (does not appear in the "run model(s)" page whereas it appears in the other pages (empty parameters but listed).

- I tried to save the plots of run1 but I get the following

Latex including various packages is needed to create PDF output

which one?

I use to create pdf with Rmarkdown.


Many thanks

Nicolas


________________________________
De : RichardHooijmaijers <notifications@github.com>
Envoyé : mercredi 18 décembre 2019 09:09
À : nlmixrdevelopment/nlmixr
Cc : SIMON Nicolas; Comment
Objet : Re: [nlmixrdevelopment/nlmixr] shinymixR (#256)


I did additional testing on a windows platform and things seems to run without a problem for me. It could be that you are missing a vital package for the app, could you try and install shinywidgets and try again?:
install.packages("shinyWidgets")

-

**Comment by RichardHooijmaijers** [comment]
Great to hear that it runs for you now! I saw there was a minor issue with updating in the app for the run model widget. Likely if you restart the app it would show up. I made small update so that it will immediately show up, you can reinstall the package for this. The latex message is just a note to let users know that they need latex to generate a PDF file. FYI, the latex package used to generate output are: geometry, graphicx, longtable, amsfonts, booktabs, fancyhdr, lastpage, hyperref, bookmark, caption, listings and float. Depending on your latex installation it will install these when needed.
